name: Changesets
description: A GitHub action to automate releases with Changesets
runs:
  using: "node12"
  main: "dist/index.js"
inputs:
  publish:
    description: "The command to use to build and publish packages"
    required: false
  version:
    description: "The command to update version, edit CHANGELOG, read and delete changesets. Default to `changeset version` if not provided"
    required: false
outputs:
  published:
    description: A boolean value to indicate whether a publishing is happened or not
branding:
  icon: "package"
  color: "blue"
