name: Changesets
description: A GitHub action to automate releases with Changesets
runs:
  using: "node24"
  main: "dist/index.js"
inputs:
  github-token:
    description: "The GitHub token to use for authentication. Defaults to the GitHub-provided token."
    required: false
    default: ${{ github.token }}
  publish:
    description: "The command to use to build and publish packages"
    required: false
  version:
    description: "The command to update version, edit CHANGELOG, read and delete changesets. Default to `changeset version` if not provided"
    required: false
  cwd:
    description: Sets the cwd for the node process. Default to `process.cwd()`
    required: false
  commit:
    description: |
      The commit message. Default to `Version Packages`
    required: false
  title:
    description: The pull request title. Default to `Version Packages`
    required: false
  setupGitUser:
    description: Sets up the git user for commits as `"github-actions[bot]"`. Default to `true`
    required: false
    default: true
  createGithubReleases:
    description: "A boolean value to indicate whether to create Github releases after `publish` or not"
    required: false
    default: true
  commitMode:
    description: >
      An enum to specify the commit mode. Use "git-cli" to push changes using the Git CLI,
      or "github-api" to push changes via the GitHub API. When using "github-api",
      all commits and tags are signed using GitHub's GPG key and attributed to the user
      or app who owns the GITHUB_TOKEN.
    required: false
    default: "git-cli"
  prBranchSuffix:
    description: The suffix to include after `changeset-release/` in the PR branch. Defaults to the `branch` variable.
    required: false
  branch:
    description: Sets the branch in which the action will run. Default to `github.ref_name` if not provided
    required: false
outputs:
  published:
    description: A boolean value to indicate whether a publishing is happened or not
  publishedPackages:
    description: >
      A JSON array to present the published packages. The format is `[{"name": "@xx/xx", "version": "1.2.0"}, {"name": "@xx/xy", "version": "0.8.9"}]`
  hasChangesets:
    description: A boolean about whether there were changesets. Useful if you want to create your own publishing functionality.
  pullRequestNumber:
    description: The pull request number that was created or updated
branding:
  icon: "package"
  color: "blue"
