name: Changesets
description: A GitHub action to automate releases with Changesets
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  publish:
    description: "The command used to build and publish packages."
    required: false
  version:
    description: "The command to update the version, edit the CHANGELOG, and manage changesets. Defaults to `changeset version` if not provided."
    required: false
  cwd:
    description: "The working directory for the process, useful when the project is not in the root. Defaults to `process.cwd()`."
    required: false
  commit:
    description: "The commit message for version updates. Defaults to `Version Packages`."
    required: false
  title:
    description: "The title for the version update pull request. Defaults to `Version Packages`."
    required: false
  setupGitUser:
    description: 'Configures the Git user for commits as `"github-actions[bot]"`. Defaults to `true`.'
    required: false
    default: true
  createGithubReleases:
    description: "Whether to create a GitHub release after publishing. Defaults to `true`."
    required: false
    default: true
  draftGithubReleases:
    description: "Whether to publish the GitHub release as a draft (unpublished). Defaults to `false`."
    required: false
    default: false
  branch:
    description: "The branch in which the action will run. Defaults to `github.ref_name` if not provided."
    required: false
outputs:
  published:
    description: A boolean value to indicate whether a publishing is happened or not
  publishedPackages:
    description: >
      A JSON array to present the published packages. The format is `[{"name": "@xx/xx", "version": "1.2.0"}, {"name": "@xx/xy", "version": "0.8.9"}]`
  hasChangesets:
    description: A boolean about whether there were changesets. Useful if you want to create your own publishing functionality.
  pullRequestNumber:
    description: The pull request number that was created or updated
branding:
  icon: "package"
  color: "blue"
