name: Setup CI

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: ".node-version"
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
