name: Changesets - PR Status
description: Generate the changesets status in PRs
runs:
  using: node24
  main: ../dist/pr-status.js
inputs: {}
outputs:
  comment-body:
    description: The generated comment body to present the changesets status in PRs.
branding:
  icon: package
  color: blue
