name: Changesets - Publish
description: Publish packages to npm
runs:
  using: node24
  main: ../dist/publish.js
inputs:
  github-token:
    description: "The GitHub token to use for authentication. Defaults to the GitHub-provided token."
    required: false
    default: ${{ github.token }}
  script:
    description: "The command to use to publish packages"
    required: false
  create-github-releases:
    description: "Whether to create Github releases after publish"
    required: false
    default: true
outputs:
  published:
    description: "A boolean value to indicate whether a publishing has happened or not"
  publishedPackages:
    description: >
      A JSON array to present the published packages. The format is `[{"name": "@xx/xx", "version": "1.2.0"}, {"name": "@xx/xy", "version": "0.8.9"}]`
branding:
  icon: package
  color: blue
